### ISSUE TITLE
3D implementation

### ISSUE THREAD

**Issue by mariosgeo** [heronimus/Inpainting-GPU#1]
Hi,

Useful code, thanks of the contribution. Is it possible to expand the inpaintig in 3D, if I provide an (m,n,z) array and the corresponding 3d mask array? 

(similar to the inpainting implementation of scikit) 

Thanks in advance

**Comment by heronimus** [comment]
Hi @mariosgeo , I know it's too late to reply, sorry I'm not actively maintaining this repo right now and missed these open issues. 

I don't think you can directly use a 3D array (tensor) with a 3D mask array since this Inpainting method is using the 2D Heat equation.  Theoretically, if you can convert the 3D tensor into a bunch series of a 2D matrix that will be possible or maybe change the method using the 3D Heat equation, but I'm not sure about that. 

I recommend you to check out this new CVPR 2020 paper about 3D photo inpainting (https://github.com/vt-vl-lab/3d-photo-inpainting) and watch the demo https://shihmengli.github.io/3D-Photo-Inpainting/.

Thanks!
